language: scala

git:
  depth: false # Avoid sbt-dynver not seeing the tag

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version
env:
  matrix:
    - TRAVIS_JDK=8

script:
  # Code validations
  - scripts/validate-code-style || travis_terminate 1;
  - sbt +test || travis_terminate 1;
  - sbt +publishLocal || travis_terminate 1;
  - sbt plugin/scripted || travis_terminate 1;
  # Generate documentation
  - sbt docs/webStage || travis_terminate 1;

deploy:
  # Publishing documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    local_dir: docs/target/web/stage
    target_branch: gh-pages
    on:
      branch: master

  # Publishing snapshot artifacts
  - provider: script
    skip_cleanup: true
    script: scripts/publish-snapshots
    on:
      branch: master
      tags: false # Disable publishing for release tags

cache:
  directories:
  - $HOME/.jabba/jdk
  - $HOME/.ivy2/cache
  - $HOME/.sbt/
